using CoreGraphics; using ExtAppraisalApp; using ExtAppraisalApp.Services; using Foundation; using System; using System.Collections.Generic; using UIKit; using AppraisalApp.Utilities; using System.Reflection.Emit; using System.Diagnostics; using AppraisalApp.Models; using Xamarin.Forms;

namespace AppraisalApp {     public partial class OptionPopUp : UIViewController     {
        partial void BtnSave_Activated(UIBarButtonItem sender)
        {
            throw new NotImplementedException();
        }


        public OptionPopUp (IntPtr handle) : base (handle)         {         }          StackLayout contentview = new StackLayout();                   public override void ViewDidLoad()         {             int y = 20;             foreach(var option in AppDelegate.appDelegate.fctoption){                 if(option.Caption==AppDelegate.appDelegate.FactoryOptionSelected)                 {                                          foreach (var question in option.questions)                     {                         UISwitch switchele = new UISwitch();                         switchele.On = Convert.ToBoolean(question.isSelected);                         UILabel label = new UILabel();                         switchele.Frame = new CGRect(20, y+33, 500, 100);                         label.Frame= new CGRect(80, y, 500, 100);                         // ((switchele)Control).CheckedChange += OnCheckedChange; " to "((Xamarin.Forms.Switch)Element).Toggled += SwitchEffect_Toggled; "                          y = y + 50;                         label.UserInteractionEnabled = true;                         label.Text = question.displayName;                         this.View.AddSubview(switchele);                         this.View.AddSubview(label);                     }                   }             }           }     } } 