// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AppraisalApp.Views
{
	public partial class AdditionDesc : UITextView
	{
		public AdditionDesc (IntPtr handle) : base (handle)
		{
		}
	}
}
