// This file has been autogenerated from a class added in the UI designer.

using System;
using ExtAppraisalApp.Services;
using Foundation;
using UIKit;

namespace ExtAppraisalApp
{
	public partial class LoginViewController : UIViewController
	{
        partial void BtnGetStart_TouchUpInside(UIButton sender)
        {
            string code = null;


            try
            {

                code = ServiceFactory.getWebServiceHandle().ValidateZipDealer(Convert.ToInt32(txtZip.Text));
                if (code != null)
                {
                    if (UIDevice.CurrentDevice.UserInterfaceIdiom == UIUserInterfaceIdiom.Pad)
                    {

                        var vehicleInfo = Storyboard.InstantiateViewController("DecodeViewController");
                        vehicleInfo.ModalPresentationStyle = UIModalPresentationStyle.FormSheet;
                        this.PresentModalViewController(vehicleInfo, true);

                    }
                    else
                    {
                        var vehicleInfo = Storyboard.InstantiateViewController("DecodeViewController");
                        this.PresentModalViewController(vehicleInfo, true);

                    }


                }
                else
                {
                    //Create Alert
                    var okAlertController = UIAlertController.Create("Title", "Please Enter valid ZIP/Dealer Code", UIAlertControllerStyle.Alert);

                    //Add Action
                    okAlertController.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, null));

                    // Present Alert
                    PresentViewController(okAlertController, true, null);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);

            }

        }






        public LoginViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            txtZip.KeyboardType = UIKeyboardType.NumberPad;
            txtZip.ReturnKeyType = UIReturnKeyType.Send;
            txtZip.BorderStyle = UITextBorderStyle.None;
            txtZip.MinimumFontSize = 17f;
            txtZip.AdjustsFontSizeToFitWidth = true;
        }


    }
	
}
