using CoreGraphics; using ExtAppraisalApp; using ExtAppraisalApp.Services; using Foundation; using System; using System.Collections.Generic; using UIKit; using AppraisalApp.Utilities; using System.Reflection.Emit; using System.Diagnostics; using AppraisalApp.Models; using Xamarin.Forms;

namespace ExtAppraisalApp {     public partial class OptionPopUp : UIViewController     {
        partial void BtnSave_Activated(UIBarButtonItem sender)
        {
            this.DismissModalViewController(true);
        }          partial void BtnCancel_Activated(UIBarButtonItem sender)
        {
            this.DismissModalViewController(true);
        }          void Switchele_ValueChanged(object sender, EventArgs e)
        {             UISwitch switchvalue = (UISwitch)sender;             int value = Convert.ToInt32(switchvalue.Tag);             foreach (var option in AppDelegate.appDelegate.fctoption)             {                 if (option.Caption == AppDelegate.appDelegate.FactoryOptionSelected)                 {                     List<FactoryOptionsKBB>  factoryOption= new  List<FactoryOptionsKBB>();                      foreach (var question in option.questions)                     {                        // AppDelegate.appDelegate.factoryOptionsKBB = question;                                                   if(question.optionId==value)                         {                                                          if(switchvalue.On){                                 question.isSelected = "true";                              }                             else{                                 question.isSelected = "false";                             }                          }                         // AppDelegate.appDelegate.factoryOptionsKBB.Add(question);                      }
                  
                }             }         }  


        public OptionPopUp (IntPtr handle) : base (handle)         {         }          StackLayout contentview = new StackLayout();                   public override void ViewDidLoad()         {             int y = 20;             foreach(var option in AppDelegate.appDelegate.fctoption){                 if(option.Caption==AppDelegate.appDelegate.FactoryOptionSelected)                 {                                          foreach (var question in option.questions)                     {                         UISwitch switchele = new UISwitch();                         switchele.On = Convert.ToBoolean(question.isSelected);                         switchele.Tag = question.optionId;                         switchele.ValueChanged+=Switchele_ValueChanged;                         UILabel label = new UILabel();                         switchele.Frame = new CGRect(20, y+33, UIScreen.MainScreen.Bounds.Width, 100);                         label.Frame= new CGRect(80, y, UIScreen.MainScreen.Bounds.Width, 100);                          y = y + 50;                         label.UserInteractionEnabled = true;                         label.Text = question.displayName;                         this.View.AddSubview(switchele);                         this.View.AddSubview(label);                     }                   }             }           }     } } 